module.exports = {
    dbpath : "mongodb://localhost/mkbandios",
    port : 3333,
    loglevel : 'debug',
    host : "http://andios.mavikentbilisim.com/",
    izinliUrlListesi : [
    "/",
    "/sayfalar/giris",
    "/hesap/giris",
    "/hesap/cikis",
    "/hesap/kaydol",
    "/sayfalar/kaydol",
    "/kurumsalizinler/ekle",
    "/versiyon/kontrolet",
    "/hakkimizda/getir",
    "/bayiler/ara",
    "/iletisim/getir",
    "/hizmetler/ara",
    "/haberler/ara",
    "/etkinlikler/ara",
    "/duyurular/ara",
    "/uretim/ara",
    "/isteksikayet/ekle",
    "/fiyatlistesi/ara",
    "/ikpolitikasi/ara",
    "/isstaj/ekle",
    "/sertifikalar/ara",
    "/kurumsalvideo/ara",
    "/kurumsalfotogaleri/ara",
    "/urunler/ara",
    "/projeler/ara",
    "/siksorular/ara",
    "/bilgibankasi/ara",
    "/kurumsalizinler/getir",
    "/sihirbaz/baslat",
    "yuklemeler"
  ]
};
